---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 1h0m0s
  ref:
    branch: main
  url: https://github.com/fluxcd/flux2

